In [11]:
from keras.preprocessing.text import Tokenizer
from keras.datasets import imdb
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense, Embedding, Flatten, LSTM, GRU, Bidirectional

In [2]:
(X_train,y_train), (X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [3]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [4]:
X_train.shape

(25000, 50)

LSTM

In [5]:
model = Sequential()

model.add(Embedding(10000, output_dim=2, input_length=50))
model.add(LSTM(32, return_sequences=False))
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 2)             20000     
                                                                 
 lstm (LSTM)                 (None, 32)                4480      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 24,513
Trainable params: 24,513
Non-trainable params: 0
_________________________________________________________________


In [6]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics='acc')
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 52s 57ms/step - loss: 0.5303 - acc: 0.7208 - val_loss: 0.4328 - val_acc: 0.8037
Epoch 2/5
782/782 [==============================] - 11s 14ms/step - loss: 0.3514 - acc: 0.8456 - val_loss: 0.4056 - val_acc: 0.8173
Epoch 3/5
782/782 [==============================] - 11s 13ms/step - loss: 0.2987 - acc: 0.8766 - val_loss: 0.4249 - val_acc: 0.8111
Epoch 4/5
782/782 [==============================] - 9s 11ms/step - loss: 0.2690 - acc: 0.8898 - val_loss: 0.4568 - val_acc: 0.8066
Epoch 5/5
782/782 [==============================] - 8s 11ms/step - loss: 0.2444 - acc: 0.9045 - val_loss: 0.4486 - val_acc: 0.8042


In [7]:
test_data = X_test[0].reshape(1,-1)
model.predict(test_data)

1/1 [==============================] - 0s 371ms/step


array([[0.40839642]], dtype=float32)

GRU

In [8]:
model = Sequential()

model.add(Embedding(10000, output_dim=2, input_length=50))
model.add(GRU(32, return_sequences=False))   # 32 gru cells
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 50, 2)             20000     
                                                                 
 gru (GRU)                   (None, 32)                3456      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 23,489
Trainable params: 23,489
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics='acc')
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 29s 33ms/step - loss: 0.5202 - acc: 0.7160 - val_loss: 0.4079 - val_acc: 0.8120
Epoch 2/5
782/782 [==============================] - 8s 11ms/step - loss: 0.3520 - acc: 0.8473 - val_loss: 0.4177 - val_acc: 0.8130
Epoch 3/5
782/782 [==============================] - 9s 11ms/step - loss: 0.3027 - acc: 0.8742 - val_loss: 0.4178 - val_acc: 0.8149
Epoch 4/5
782/782 [==============================] - 9s 11ms/step - loss: 0.2679 - acc: 0.8932 - val_loss: 0.4519 - val_acc: 0.8071
Epoch 5/5
782/782 [==============================] - 9s 11ms/step - loss: 0.2458 - acc: 0.9030 - val_loss: 0.4717 - val_acc: 0.7951


In [10]:
test_data = X_test[0].reshape(1,-1)
model.predict(test_data)

1/1 [==============================] - 0s 293ms/step


array([[0.37042874]], dtype=float32)

Bi-RNN

In [12]:
model = Sequential()

model.add(Embedding(10000, output_dim=2, input_length=50))
model.add(Bidirectional(LSTM(32, return_sequences=False)))   # Biderctional ke baad RNN or LSTM kuch bhi likh skte hai
model.add(Dense(1,activation='sigmoid'))

model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 50, 2)             20000     
                                                                 
 bidirectional (Bidirectiona  (None, 64)               8960      
 l)                                                              
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 29,025
Trainable params: 29,025
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics='acc')
model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 [==============================] - 33s 37ms/step - loss: 0.4908 - acc: 0.7493 - val_loss: 0.4184 - val_acc: 0.8074
Epoch 2/5
782/782 [==============================] - 13s 17ms/step - loss: 0.3466 - acc: 0.8516 - val_loss: 0.4126 - val_acc: 0.8126
Epoch 3/5
782/782 [==============================] - 12s 15ms/step - loss: 0.2985 - acc: 0.8758 - val_loss: 0.4173 - val_acc: 0.8078
Epoch 4/5
782/782 [==============================] - 15s 19ms/step - loss: 0.2676 - acc: 0.8922 - val_loss: 0.4348 - val_acc: 0.8003
Epoch 5/5
782/782 [==============================] - 12s 15ms/step - loss: 0.2452 - acc: 0.9022 - val_loss: 0.4838 - val_acc: 0.7972


In [14]:
test_data = X_test[0].reshape(1,-1)
model.predict(test_data)

1/1 [==============================] - 1s 660ms/step


array([[0.6201727]], dtype=float32)

In [15]:
y_test[0]

0