In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                           "dswithbappy with dswithbappy",
                           "people write comment",
                           "dswithbappy write comment"],"output":[1,1,0,0]})
df

text  output
0      people watch dswithbappy       1
1  dswithbappy with dswithbappy       1
2          people write comment       0
3     dswithbappy write comment       0

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [8]:
bow = cv.fit_transform(df['text'])

In [5]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'with': 4, 'write': 5, 'comment': 0}


In [6]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 1 1 1 0 0]]
[[0 2 0 0 1 0]]
[[1 0 1 0 0 1]]
[[1 1 0 0 0 1]]


In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range = (2,2))

In [11]:
bow = cv.fit_transform(df['text'])

In [12]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy with': 0, 'with dswithbappy': 5, 'people write': 3, 'write comment': 6, 'dswithbappy write': 1}


In [13]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())

[[0 0 1 0 1 0 0]]
[[1 0 0 0 0 1 0]]
[[0 0 0 1 0 0 1]]
[[0 1 0 0 0 0 1]]


In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [15]:
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.44809973, 0.55349232, 0.70203482, 0.        ,
        0.        ],
       [0.        , 0.78722298, 0.        , 0.        , 0.61666846,
        0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.        ,
        0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.        ,
        0.61366674]])

In [16]:
print(tfidf.idf_)

[1.51082562 1.22314355 1.51082562 1.91629073 1.91629073 1.51082562]


In [18]:
print(tfidf.get_feature_names_out())

['comment' 'dswithbappy' 'people' 'watch' 'with' 'write']


word2vec

glove

is remaining